version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://1.117.176.111:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  #  docker run -d  \
  #  -e ZK_HOSTS=localhost:2181 \
  #  -p 9000:9000 \
  #  moech/kafka-manager

#  kafka-manager:
#    image: moech/kafka-manager
#    ports:
#      - "9027:9000"
#    environment:
#      ZK_HOSTS: zookeeper:2181

#  docker run -p 8080:8080 -e KAFKA_BROKERS=host.docker.internal:9092 quay.io/cloudhut/kowl:master

  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - "9028:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092