version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://1.117.176.111:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#      - '9093:9093'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://1.117.176.111:9093
#      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
#
#    depends_on:
#        - zookeeper
  #  docker run -d  \
  #  -e ZK_HOSTS=localhost:2181 \
  #  -p 9000:9000 \
  #  moech/kafka-manager

#  kafka-manager:
#    image: moech/kafka-manager
#    ports:
#      - "9027:9000"
#    environment:
#      ZK_HOSTS: zookeeper:2181

#  docker run -p 8080:8080 -e KAFKA_BROKERS=host.docker.internal:9092 quay.io/cloudhut/kowl:master

#  docker run -d -p 8889:8889 freakchicken/kafka-ui-lite
  kafka-ui-lite:
    image: freakchicken/kafka-ui-lite
    ports:
      - "8080:8080"


  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - "9028:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092