version: '3.1'
services:
  docker-registry:
    image: registry:2
    ports:
      - 443:443
    volumes:
      - /usr/local/registry:/var/lib/registry
      - ./certs:/certs

  frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8080:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.204.131
      - ENV_DOCKER_REGISTRY_PORT=5000
