version: '2'

services:
  mysql-slave:
    image: 'bitnami/mysql:8.0'
    ports:
      - 7001:3306
    volumes:
      - ./mysql_slave_data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=my_database
      - MYSQL_MASTER_HOST=93.188.163.116
      - MYSQL_MASTER_PORT_NUMBER=7000
      - MYSQL_MASTER_ROOT_PASSWORD=my_root_password
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
