version: '3.1'

services:

  es:
    ports:
      - 9200:9200
    image: elasticsearch:7.13.1
    container_name: es
    environment:
      - node.name=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es
      - cluster.initial_master_nodes=es
    ulimits:
      memlock:
        soft: -1
        hard: -1

  appsearch:
    container_name: appsearch
    image: docker.elastic.co/enterprise-search/enterprise-search:7.13.1
    environment:
      - elasticsearch.host='http://es:9200'
      - elasticsearch.username=elastic
      - elasticsearch.password=changeme
      - allow_es_settings_modification=true
      - secret_management.encryption_keys=[4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09]
    ports:
      - 3002:3002
  
  kibana:
    container_name: kibana
    image: jamesgarside/kibana
    ports:    
      - 5601:5601
    environment:
      SERVER_NAME: "kibana.example.org"
      ELASTICSEARCH_HOSTS: "http://es:9200"