version: '3.1'

services:
  fluent:
    image: fluent/fluent-bit:1.4
    network_mode: host
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: localhost:24224
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
